# Generated by Django 2.2.4 on 2024-07-14 21:38

import Semi_restfull_validate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Semi_restfull_validate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(validators=[Semi_restfull_validate.models.validate_release_date_in_past]),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
